<?php

namespace AppBundle\Repository;

/**
 * Categories_EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categories_EventRepository extends \Doctrine\ORM\EntityRepository
{
}
