<?php

namespace AppBundle\Repository;

/**
 * CommentaireVeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireVeloRepository extends \Doctrine\ORM\EntityRepository
{
}
