<?php
namespace AppBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository  extends \Doctrine\ORM\EntityRepository
{

}