<?php

namespace AppBundle\Repository;

/**
 * LigneDeCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneDeCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
