<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findArray($array)
{
    $qb = $this->createQueryBuilder('v')
        ->Select('v')
        ->Where('v.id IN (:array)')
        ->setParameter('array', $array);
    return $qb->getQuery()->getResult();
}
}
