<?php

namespace AppBundle\Repository;

/**
 * RatingVeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingVeloRepository extends \Doctrine\ORM\EntityRepository
{
    public function calculateRating($idVelo)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        return $qb
            ->select('AVG(r.rating)')
            ->from('AppBundle:RatingVelo', 'r')
            ->where('r.idVelo = ?1')
            ->setParameter('1',$idVelo)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
