<?php

namespace AppBundle\Repository;

/**
 * roduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
