ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Ecommerce:index }
ecommerce_listevent:
    path:     /list_event
    defaults: { _controller: EcommerceBundle:Ecommerce:AfficherListeEvent }
details_events:
    path:     /details_event/{id}
    defaults: { _controller: EcommerceBundle:Ecommerce:detailsEvent }
participation_event:
    path:   /participe/{id}
    defaults: { _controller: EcommerceBundle:Ecommerce:Participer }
participation_annuler:
    path:   /annuler/{id_participation}
    defaults: { _controller: EcommerceBundle:Ecommerce:AnnulerParticipation }
dateasc_event:
    path: /datedsc
    defaults: { _controller: EcommerceBundle:Ecommerce:Dateasc }
datedesc_event:
    path: /dateasc
    defaults: { _controller: EcommerceBundle:Ecommerce:Datedesc }
recherche_event:
    path: /recherche
    defaults: { _controller: EcommerceBundle:Ecommerce:search }
supprimer_comm:
    path:   /supp/{id_com}
    defaults: { _controller: EcommerceBundle:Ecommerce:SupprimerCommentaire }
modifier_comm:
    path:   /modifier/{id_com}
    defaults: { _controller: EcommerceBundle:Ecommerce:ModifierCommentaire }