user_page_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
user_inscription:
    path:     /register
    defaults: { _controller: UserBundle:Default:inscription}
list_event:
    path: /list_event
    defaults: { _controller: UserBundle:Default:Event}
EspaceAcheteur:
    path:     /EspaceAcheteur
    defaults: { _controller: UserBundle:Default:EspaceAcheteur}
rendezvous:
    path:     /rendezvous/{id}
    defaults: { _controller: UserBundle:Default:rendezvous}
EspaceReparateur:
    path:     /EspaceReparateur
    defaults: { _controller: UserBundle:Default:EspaceReparateur}
EspaceRdv:
    path:     /EspaceRdv/{id}
    defaults: { _controller: UserBundle:Default:EspaceRdv}
index:
    path:     /index
    defaults: { _controller: UserBundle:Default:indexx }
Reparateurs:
    path:     /Reparateurs
    defaults: { _controller: UserBundle:Default:Reparateurs }
mail:
    path:     /mail
    defaults: { _controller: UserBundle:Default:mail}
del:
    path:     /del/{cin}
    defaults: { _controller: UserBundle:Default:del}
validrendezvous:
    path:     /validrendezvous/{id}
    defaults: { _controller: UserBundle:Default:validrendezvous}
listrendezvous:
    path:     /listrendezvous
    defaults: { _controller: UserBundle:Default:listrendezvous}
MaRendezVousValid:
    path:     /MaRendezVousValid
    defaults: { _controller: UserBundle:Default:MaRendezVousValid}
reclamation:
    path:     /reclamation
    defaults: { _controller: UserBundle:Default:reclamation}
mesreclamation:
    path:     /mesreclamation
    defaults: { _controller: UserBundle:Default:mesreclamation}
Suppreclamation:
    path:     /Suppreclamation/{reference}
    defaults: { _controller: UserBundle:Default:Suppreclamation}
Modifireclamation:
    path:     /Modifireclamation/{reference}
    defaults: { _controller: UserBundle:Default:Modifireclamation}
Suppriml:
    path:     /Suppriml/{reference}
    defaults: { _controller: UserBundle:Default:Suppriml}
Supprimes:
    path:     /Supprimes/{Cin}
    defaults: { _controller: UserBundle:Default:Supprimes}
Modifirendezvous:
    path:     /Modifirendezvous/{Cin}
    defaults: { _controller: UserBundle:Default:Modifirendezvous}
refuserrendezvous:
    path:     /refuserrendezvous/{id}
    defaults: { _controller: UserBundle:Default:refuserrendezvous}
blog:
    path:     /blog
    defaults: { _controller: UserBundle:Default:blog}
ajouterUneEtoile:
    path:     /ajouterUneEtoile/{id}/{nombre}
    defaults: { _controller: UserBundle:Default:ajouterUneEtoile }
Comment:
    path:     /Comment
    defaults: { _controller: UserBundle:Default:Comment}
search:
    path:     /search
    defaults: { _controller: UserBundle:Default:search}

